---
- name: Execução | Atualizar servidores Linux
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Atualizar pacotes (Debian/Ubuntu)
      apt:
        upgrade: dist
        autoremove: no
      when: ansible_os_family == "Debian"

    - name: Atualizar pacotes (RHEL/Oracle)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Verificar se reboot é necessário (Debian)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"

    - name: Informar necessidade de reboot
      debug:
        msg: "ATENÇÃO: Reboot necessário após atualização."
      when:
        - reboot_required.stat is defined
        - reboot_required.stat.exists
